server:
  port: 8080
spring:
  profiles:
    active:
      - dev
  datasource:
    dynamic:
      p6spy: true
      druid:
        initial-size: 2
        max-active: 100
        max-wait: 20000
        min-idle: 0
        test-on-borrow: true
        test-on-return: true
      primary: master
      datasource:
        master:
          url: jdbc:mysql://${db.slave_1.host}:${db.slave_1.port}/${db.name}?useUnicode=true&useSSL=false&characterEncoding=utf8
          username: ${db.master.username}
          password: ${db.master.password}
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid:
              initial-size: 5
        slave_1:
          url: jdbc:mysql://${db.slave_1.host}:${db.slave_1.port}/${db.name}?useUnicode=true&useSSL=false&characterEncoding=utf8
          username: ${db.slave_1.username}
          password: ${db.slave_1.password}
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid:
            initial-size: 5
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss